services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      AZURE_OPENAI_API_KEY: "1811695dbd824d2aaf66323f8346b894"
      AZURE_OPENAI_ENDPOINT: "https://eastus.api.cognitive.microsoft.com/"
